repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-aws-credentials

  # have to maintain ruff version in two places
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.15.17
  #   hooks:
  #     - id: ruff-check
  #       args: [--fix]
  #     - id: ruff-format

  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 4.2.2
  #   hooks:
  #   - id: sqlfluff-fix
  #     args: [--dialect, postgres]
  #     files: ^sql/

  # needs uv venv with all dependencies
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v2.1.0
  #   hooks:
  #     - id: mypy
  #       args: [--config-file=./pyproject.toml]
  #       additional_dependencies: [pydantic]

  - repo: local
    hooks:

      - id: fmt
        name: fmt
        language: system
        entry: make fmt
        pass_filenames: false # Do not pass filenames = runs on all files and not only modified ones

      - id: lint
        name: lint
        language: system
        entry: make lint
        pass_filenames: false

      - id: typecheck
        name: typechk
        language: system
        entry: make typechk
        pass_filenames: false
