services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: on-failure
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DN_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./sql/:/docker-entrypoint-initdb.d/sql/
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
